First real attempt

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,7 +40,7 @@ jobs:
       - name: Add msbuild to PATH
         uses: microsoft/setup-msbuild@v1.0.2
       - name: Build
-        run: msbuild src -p:Configuration=Release -restore -m
+        run: msbuild src -p:Configuration=Release -restore -m -verbosity:minimal
       - name: Upload packages
         uses: actions/upload-artifact@v2.2.4
         with:
@@ -50,8 +50,7 @@ jobs:
             zip/
             assets/
           retention-days: 1
-      - name: Run unit tests (LearningTransport only)
-        if: matrix.transport == 'LearningTransport'
+      - name: Run unit tests
         shell: pwsh
         run: |
           $exitCode = 0
@@ -71,190 +70,194 @@ jobs:
         with:
           name: acceptance-tests
           path: src/*.AcceptanceTests/bin/Release/
+          retention-days: 1
 
-  part2:
+  acceptance-tests:
     needs: build
+    name: AcceptanceTests-${{ matrix.name }}
     runs-on: windows-2019
+    strategy:
+      matrix:
+        include:
+          - name: LearningTransport
+            transport: LearningTransport
+            customization: ConfigureEndpointLearningTransport
+          - name: Msmq
+            transport: Msmq
+            customization: ConfigureEndpointMsmqTransport
+          - name: SqlServer
+            transport: SqlServer
+            customization: ConfigureEndpointSqlServerTransport
+          - name: RabbitMQ-Conventional
+            transport: RabbitMQ
+            customization: ConfigureEndpointRabbitMQConventionalRoutingTransport
+          - name: RabbitMQ-Direct
+            transport: RabbitMQ
+            customization: ConfigureEndpointRabbitMQDirectRoutingTransport
+          - name: AzureServiceBus-EndpointTopology
+            transport: AzureServiceBus
+            customization: ConfigureEndpointAzureServiceBusEndpointTopologyTransport
+          - name: AzureServiceBus-ForwardingTopology
+            transport: AzureServiceBus
+            customization: ConfigureEndpointAzureServiceBusForwardingTopologyTransport
+          - name: AzureStorageQueues
+            transport: AzureStorageQueues
+            customization: ConfigureEndpointAzureStorageQueueTransport
+          - name: SQS
+            transport: SQS
+            customization: ConfigureEndpointSQSTransport
+          - name: AzureServiceBusNetStandard
+            transport: AzureServiceBusNetStandard
+            customization: ConfigureEndpointAzureServiceBusNetStandardTransport
+      fail-fast: false
+    env:
+      ServiceControl.AcceptanceTests.Transport: ${{ matrix.transport }}
+      ServiceControl.AcceptanceTests.TransportCustomization: ${{ matrix.customization }}
+      ServiceControl/LicenseText: ${{ secrets.SERVICECONTROL_LICENSETEXT }}
+      ServiceControl.Audit/LicenseText: ${{ secrets.AUDIT_LICENSETEXT }}
+      Monitoring/LicenseText: ${{ secrets.MONITORING_LICENSETEXT }}
     steps:
       - name: Download acceptance tests
         uses: actions/download-artifact@v2.0.10
         with:
           name: acceptance-tests
       - run: ls -R
+      - name: Azure login
+        uses: azure/login@v1.3.0
+        with:
+          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
+      - name: Setup SQL Server
+        if: matrix.transport == 'SqlServer'
+        uses: Particular/install-sql-server-action@v1.0.0
+        with:
+          connection-string-env-var: ServiceControl.AcceptanceTests.ConnectionString
+          catalog: nservicebus
+      - name: Setup RabbitMQ
+        if: matrix.transport == 'RabbitMQ'
+        id: setup-rabbitmq
+        shell: pwsh
+        run: |
+          # Retrieve the Azure region in which this workflow is running. This region should be used to create addtional resources.
+          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
+          $region = $hostInfo.compute.location
 
-#  acceptance-tests:
-#    needs: build
-#    name: AcceptanceTests-${{ matrix.name }}
-#    runs-on: windows-2019
-#    strategy:
-#      matrix:
-#        include:
-#          - name: LearningTransport
-#            transport: LearningTransport
-#            customization: ConfigureEndpointLearningTransport
-#          - name: Msmq
-#            transport: Msmq
-#            customization: ConfigureEndpointMsmqTransport
-#          - name: SqlServer
-#            transport: SqlServer
-#            customization: ConfigureEndpointSqlServerTransport
-#          - name: RabbitMQ-Conventional
-#            transport: RabbitMQ
-#            customization: ConfigureEndpointRabbitMQConventionalRoutingTransport
-#          - name: RabbitMQ-Direct
-#            transport: RabbitMQ
-#            customization: ConfigureEndpointRabbitMQDirectRoutingTransport
-#          - name: AzureServiceBus-EndpointTopology
-#            transport: AzureServiceBus
-#            customization: ConfigureEndpointAzureServiceBusEndpointTopologyTransport
-#          - name: AzureServiceBus-ForwardingTopology
-#            transport: AzureServiceBus
-#            customization: ConfigureEndpointAzureServiceBusForwardingTopologyTransport
-#          - name: AzureStorageQueues
-#            transport: AzureStorageQueues
-#            customization: ConfigureEndpointAzureStorageQueueTransport
-#          - name: SQS
-#            transport: SQS
-#            customization: ConfigureEndpointSQSTransport
-#          - name: AzureServiceBusNetStandard
-#            transport: AzureServiceBusNetStandard
-#            customization: ConfigureEndpointAzureServiceBusNetStandardTransport
-#      fail-fast: false
-#    env:
-#      ServiceControl.AcceptanceTests.Transport: ${{ matrix.transport }}
-#      ServiceControl.AcceptanceTests.TransportCustomization: ${{ matrix.customization }}
-#      ServiceControl/LicenseText: ${{ secrets.SERVICECONTROL_LICENSETEXT }}
-#      ServiceControl.Audit/LicenseText: ${{ secrets.AUDIT_LICENSETEXT }}
-#      Monitoring/LicenseText: ${{ secrets.MONITORING_LICENSETEXT }}
-#    steps:
-#      - name: Download acceptance tests
-#        uses: actions/download-artifact@v2.0.10
-#        with:
-#          name: acceptance-tests
-#          path: 
-#      - name: Azure login
-#        uses: azure/login@v1.3.0
-#        with:
-#          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
-#      - name: Setup SQL Server
-#        if: matrix.transport == 'SqlServer'
-#        uses: Particular/install-sql-server-action@v1.0.0
-#        with:
-#          connection-string-env-var: ServiceControl.AcceptanceTests.ConnectionString
-#          catalog: nservicebus
-#      - name: Setup RabbitMQ
-#        if: matrix.transport == 'RabbitMQ'
-#        id: setup-rabbitmq
-#        shell: pwsh
-#        run: |
-#          # Retrieve the Azure region in which this workflow is running. This region should be used to create addtional resources.
-#          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
-#          $region = $hostInfo.compute.location
-#
-#          $hostname = "psw-rabbitmq-$(Get-Random)"
-#          echo "::set-output name=hostname::$hostname"
-#          echo "Creating RabbitMQ container $hostname in $region (This can take a while.)"
-#          $jsonResult = az container create --image rabbitmq:3-management --name $hostname --location $region --dns-name-label $hostname --resource-group GitHubActions-RG --cpu 4 --memory 16 --ports 5672 15672 --ip-address public
-#          if(!$jsonResult)
-#          {
-#            Write-Output "Failed to create RabbitMQ container"
-#            exit 1;
-#          }
-#          $details = $jsonResult | ConvertFrom-Json
-#          if (!$details.ipAddress) {
-#            Write-Output "Failed to create RabbitMQ container $hostname in $region"
-#            Write-Output $jsonResult
-#            exit 1;
-#          }
-#          $ip=$details.ipAddress.ip
-#          echo "::add-mask::$ip"
-#          echo "Tagging container image"
-#          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
-#          $ignore = az tag create --resource-id $details.id --tags Package=ServiceControl RunnerOS=${{ runner.os }} $dateTag
-#          echo "ServiceControl.AcceptanceTests.ConnectionString=host=$ip" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
-#
-#          $uri = "http://" + $ip + ":15672/api/health/checks/virtual-hosts"
-#          $tries = 0
-#          do
-#          {
-#            $response = curl $uri -u guest:guest | ConvertFrom-Json
-#            $tries++
-#            if(!$response.status)
-#            {
-#              Write-Output "No response, retrying..."
-#              Start-Sleep -m 5000
-#            }
-#          } until (($response.status) -or ($tries -ge 10))
-#          if($response.status -ne "ok")
-#          {
-#            Write-Output "Failed to connect after 10 attempts";
-#            exit 1
-#          }
-#      - name: Setup Azure Service Bus
-#        if: matrix.transport == 'AzureServiceBus' || matrix.transport == 'AzureServiceBusNetStandard'
-#        id: setup-asb
-#        shell: pwsh
-#        run: |
-#          # Retrieve the Azure region in which this workflow is running. This region should be used to create addtional resources.
-#          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
-#          $region = $hostInfo.compute.location
-#
-#          $name = "psw-asb-$(Get-Random)"
-#          echo "::set-output name=name::$name"
-#          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
-#
-#          echo "Creating Azure Service Bus namespace $name (This can take awhile.)"
-#          $details = az servicebus namespace create --resource-group GitHubActions-RG --location $region --name $name --tags Package=ServiceControl RunnerOS=${{ runner.os }} $dateTag | ConvertFrom-Json
-#
-#          echo "Getting connection string"
-#          $keys = az servicebus namespace authorization-rule keys list --resource-group GitHubActions-RG --namespace-name $name --name RootManageSharedAccessKey | ConvertFrom-Json
-#          $connectString = $keys.primaryConnectionString
-#          echo "::add-mask::$connectString"
-#
-#          echo "ServiceControl.AcceptanceTests.ConnectionString=$connectString" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
-#      - name: Setup Azure Storage Queues
-#        if: matrix.transport == 'AzureStorageQueues'
-#        id: setup-asq
-#        shell: pwsh
-#        run: |
-#          # Retrieve the Azure region in which this workflow is running. This region should be used to create addtional resources.
-#          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
-#          $region = $hostInfo.compute.location
-#
-#          $rand = Get-Random
-#          $accountname = "pswasq$($rand)"
-#          echo "::set-output name=accountname::$accountname"
-#          echo "Creating storage account"
-#          $details = az storage account create --name $accountname --resource-group GitHubActions-RG --location $region --sku Standard_LRS | ConvertFrom-Json
-#
-#          echo "Getting account access keys"
-#          $keys = az storage account keys list --account-name $accountname --resource-group GitHubActions-RG | ConvertFrom-Json
-#          $key = $keys[0].value
-#          echo "::add-mask::$key"
-#
-#          echo "Tagging storage accounts"
-#          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
-#          $ignore = az tag create --resource-id $details.id --tags Package=ServiceControl RunnerOS=${{ runner.os }} $dateTag
-#
-#          $connectString = "DefaultEndpointsProtocol=https;AccountName=$accountname;AccountKey=$key"
-#
-#          echo "ServiceControl.AcceptanceTests.ConnectionString=$connectString" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
-#
-#      - name: Run tests
-#        uses: Particular/run-tests-action@v1.0.0
-#
-#      - name: Teardown infrastructure
-#        if: ${{ always() }}
-#        shell: pwsh
-#        run: |
-#          if ('${{ matrix.transport }}' -eq 'RabbitMQ') {
-#            $ignore = az container delete --resource-group GitHubActions-RG --name ${{ steps.setup-rabbitmq.outputs.hostname }} --yes
-#          }
-#
-#          if ('${{ matrix.transport }}' -eq 'AzureServiceBus' -Or '${{ matrix.transport }}' -eq 'AzureServiceBusNetStandard') {
-#            $ignore = az servicebus namespace delete --resource-group GitHubActions-RG --name ${{ steps.setup-asb.outputs.name }}
-#          }
-#
-#          if ('${{ matrix.transport }}' -eq 'AzureStorageQueues') {
-#            $ignore = az storage account delete --resource-group GitHubActions-RG --name ${{ steps.setup-asq.outputs.accountname }} --yes
-#          }
+          $hostname = "psw-rabbitmq-$(Get-Random)"
+          echo "::set-output name=hostname::$hostname"
+          echo "Creating RabbitMQ container $hostname in $region (This can take a while.)"
+          $jsonResult = az container create --image rabbitmq:3-management --name $hostname --location $region --dns-name-label $hostname --resource-group GitHubActions-RG --cpu 4 --memory 16 --ports 5672 15672 --ip-address public
+          if(!$jsonResult)
+          {
+            Write-Output "Failed to create RabbitMQ container"
+            exit 1;
+          }
+          $details = $jsonResult | ConvertFrom-Json
+          if (!$details.ipAddress) {
+            Write-Output "Failed to create RabbitMQ container $hostname in $region"
+            Write-Output $jsonResult
+            exit 1;
+          }
+          $ip=$details.ipAddress.ip
+          echo "::add-mask::$ip"
+          echo "Tagging container image"
+          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
+          $ignore = az tag create --resource-id $details.id --tags Package=ServiceControl RunnerOS=${{ runner.os }} $dateTag
+          echo "ServiceControl.AcceptanceTests.ConnectionString=host=$ip" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
+
+          $uri = "http://" + $ip + ":15672/api/health/checks/virtual-hosts"
+          $tries = 0
+          do
+          {
+            $response = curl $uri -u guest:guest | ConvertFrom-Json
+            $tries++
+            if(!$response.status)
+            {
+              Write-Output "No response, retrying..."
+              Start-Sleep -m 5000
+            }
+          } until (($response.status) -or ($tries -ge 10))
+          if($response.status -ne "ok")
+          {
+            Write-Output "Failed to connect after 10 attempts";
+            exit 1
+          }
+      - name: Setup Azure Service Bus
+        if: matrix.transport == 'AzureServiceBus' || matrix.transport == 'AzureServiceBusNetStandard'
+        id: setup-asb
+        shell: pwsh
+        run: |
+          # Retrieve the Azure region in which this workflow is running. This region should be used to create addtional resources.
+          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
+          $region = $hostInfo.compute.location
+
+          $name = "psw-asb-$(Get-Random)"
+          echo "::set-output name=name::$name"
+          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
+
+          echo "Creating Azure Service Bus namespace $name (This can take awhile.)"
+          $details = az servicebus namespace create --resource-group GitHubActions-RG --location $region --name $name --tags Package=ServiceControl RunnerOS=${{ runner.os }} $dateTag | ConvertFrom-Json
+
+          echo "Getting connection string"
+          $keys = az servicebus namespace authorization-rule keys list --resource-group GitHubActions-RG --namespace-name $name --name RootManageSharedAccessKey | ConvertFrom-Json
+          $connectString = $keys.primaryConnectionString
+          echo "::add-mask::$connectString"
+
+          echo "ServiceControl.AcceptanceTests.ConnectionString=$connectString" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
+      - name: Setup Azure Storage Queues
+        if: matrix.transport == 'AzureStorageQueues'
+        id: setup-asq
+        shell: pwsh
+        run: |
+          # Retrieve the Azure region in which this workflow is running. This region should be used to create addtional resources.
+          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
+          $region = $hostInfo.compute.location
+
+          $rand = Get-Random
+          $accountname = "pswasq$($rand)"
+          echo "::set-output name=accountname::$accountname"
+          echo "Creating storage account"
+          $details = az storage account create --name $accountname --resource-group GitHubActions-RG --location $region --sku Standard_LRS | ConvertFrom-Json
+
+          echo "Getting account access keys"
+          $keys = az storage account keys list --account-name $accountname --resource-group GitHubActions-RG | ConvertFrom-Json
+          $key = $keys[0].value
+          echo "::add-mask::$key"
+
+          echo "Tagging storage accounts"
+          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
+          $ignore = az tag create --resource-id $details.id --tags Package=ServiceControl RunnerOS=${{ runner.os }} $dateTag
+
+          $connectString = "DefaultEndpointsProtocol=https;AccountName=$accountname;AccountKey=$key"
+
+          echo "ServiceControl.AcceptanceTests.ConnectionString=$connectString" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
+
+      - name: Run tests
+        shell: pwsh
+        run: |
+          $exitCode = 0
+          Get-ChildItem src -Recurse -Filter *.AcceptanceTests.dll | ForEach-Object {
+            echo "Running acceptance test project $($_.Name)"
+            $testPath = $_.FullName
+            dotnet test $testPath --logger "GitHubActions;report-warnings=false" -m:1
+            if ($LASTEXITCODE -ne 0) {
+              $exitCode = 1
+            }
+          }
+
+          Write-Output "Exit code = $exitCode"
+          exit $exitCode
+
+      - name: Teardown infrastructure
+        if: ${{ always() }}
+        shell: pwsh
+        run: |
+          if ('${{ matrix.transport }}' -eq 'RabbitMQ') {
+            $ignore = az container delete --resource-group GitHubActions-RG --name ${{ steps.setup-rabbitmq.outputs.hostname }} --yes
+          }
+
+          if ('${{ matrix.transport }}' -eq 'AzureServiceBus' -Or '${{ matrix.transport }}' -eq 'AzureServiceBusNetStandard') {
+            $ignore = az servicebus namespace delete --resource-group GitHubActions-RG --name ${{ steps.setup-asb.outputs.name }}
+          }
+
+          if ('${{ matrix.transport }}' -eq 'AzureStorageQueues') {
+            $ignore = az storage account delete --resource-group GitHubActions-RG --name ${{ steps.setup-asq.outputs.accountname }} --yes
+          }
